services:
  gateway:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.hostname: deploy-template
    environment:
      GATEWAY_SYSTEM_NAME: deploy-template
      GATEWAY_PUBLIC_HTTP_PORT: 80
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: deploy-template.localtest.me
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy
