name: auto-update
on:
  push:
    branches: [ master ]
jobs:
  Automatically-Update:
    name: Spenny
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: bro idk
        run: |
          mkdir ignition-data
          chmod -R g+w ignition-data
          docker-compose up -d
